# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyPhotoWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPhotoWatch
  pod 'Kingfisher', '~> 3.0'
  pod 'Hero'

  target 'MyPhotoWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyPhotoWatchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
